version: "3"

services:
  loki:

  promtail:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - aggregation

networks:
  aggregation:
    driver: bridge
